### ISSUE TITLE
ParBayesianOptimization suddenly fails while logging epoch results

### ISSUE THREAD

**Issue by hanibalSC** [cran/ParBayesianOptimization#1]
Hi,

Firstly, thanks for sharing this package. 

I am currently using it  to tune parameters for ML methods. While searching for an optimal cost parameter for the `svmLinear2` model (contained in `caret`), the optimization stopped with a sudden error after successfully completing 15 iterations.

![image](https://user-images.githubusercontent.com/47225647/117300891-5168d500-ae7a-11eb-804a-771b1c9fedba.png)

Here is the error traceback:
```Error in rbindlist(l, use.names, fill, idcol) : 
  Item 2 has 9 columns, inconsistent with item 1 which has 10 columns. To fill missing columns use fill=TRUE. 
7.
rbindlist(l, use.names, fill, idcol) 
6.
rbind(deparse.level, ...) 
5.
rbind(scoreSummary, data.table(Epoch = rep(Epoch, nrow(NewResults)), 
    Iteration = 1:nrow(NewResults) + nrow(scoreSummary), inBounds = rep(TRUE, 
        nrow(NewResults)), NewResults)) 
4.
addIterations(optObj, otherHalting = otherHalting, iters.n = iters.n, 
    iters.k = iters.k, parallel = parallel, plotProgress = plotProgress, 
    errorHandling = errorHandling, saveFile = saveFile, verbose = verbose, 
    ...) 
3.
ParBayesianOptimization::bayesOpt(FUN = ...
```
So somehow the data tables storing the summary information each iteration suddenly differ in the number of columns present. Is this a common bug with the ParBayesianOptimization package?

Should `fill` be set to  `TRUE` in `rbind` for robustness? Or is something more fundamental wrong?

Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by hanibalSC** [comment]
Thanks for the info.
For anyone interested in how this progresses, please refer to https://github.com/AnotherSamWilson/ParBayesianOptimization/issues/33
